### ISSUE TITLE
Namespace name `Math' does not exist 

### ISSUE THREAD

**Issue by noorbeast** [createthis/mesh_maker_vr#1]
Update: Actually this may well be from having already played with earlier release of the UI project, re copied and that seemed to resolved the issue.

**Comment by createthis** [comment]
This appears to be an issue with VR Gimbal Camera overwriting `Assets/CreateThis/Scripts/Math/Ratio.cs` with a version that is identical, except it uses a different namespace. Sorry. I must have fixed this by hand and forgotten about it. You'll also need to change line 4 in `GimbalCameraHUDFactory.cs`

**Comment by createthis** [comment]
Probably just removing the Gimbal Camera dependency is the best way forward here.

**Comment by createthis** [comment]
gah, I just remembered my copy of Amazing Wireframe Shader is slightly tricked out too. I'll include a diff and/or instructions when my fresh copy finishes compiling.

![image](https://user-images.githubusercontent.com/1695880/27982637-d42a9bfe-6374-11e7-904b-9e479bdddf4e.png)

**Comment by noorbeast** [comment]
I have just updated Unity tp 5.6.2f1 so will start from scratch, leave out VR Gimbal Camera and look forward to your tweaks for Amazing Wireframe Shader ;-)

I am really keen to get this working. I did get it to run first time round, though the radial menu was messed up, so could not really try anything.

**Comment by noorbeast** [comment]
Staring from scratch on Unity 5.6.2f1, import SteamVR, VRTK, Unity Test Tools, Simple Color Picker and The Amazing Wireframe Shader.

First issue is:

Assets/MMVR/Factory/UI/Panel/MMVR_SettingsPanelFactory.cs(11,24): error CS0234: The type or namespace name `ColorPicker' does not exist in the namespace `CreateThis.VR.UI'. Are you missing an assembly reference?

Assets/MMVR/Factory/UI/Panel/MMVR_SettingsPanelFactory.cs(13,23): error CS0234: The type or namespace name `ColorPicker' does not exist in the namespace `MMVR.Factory.UI'. Are you missing an assembly reference?


Assets/MMVR/Factory/UI/Panel/MMVR_SettingsPanelFactory.cs(18,16): error CS0246: The type or namespace name `ColorPickerProfile' could not be found. Are you missing an assembly reference?

**Comment by createthis** [comment]
Looks like you've changed your scene file. In File -> Build Settings -> Player Settings -> Scripting Define Symbols you should have this:
`AMAZING_WIREFRAME_SHADER;COLOR_PICKER`

**Comment by createthis** [comment]
BTW, I got a successful build without tweaking Wireframe Shader. The tweaks just enable to display of the face normals.

**Comment by createthis** [comment]
I've submitted a new version of VR Gimbal Camera to the Unity Asset Store. Hopefully that will resolve the `Namespace name 'Math' does not exist` issue. They take a few days to approve the change, so I'll leave this open until it is resolved upstream.

**Comment by noorbeast** [comment]
Great job, I can confirm that with the updates and patches everything now seems to work, hopefully I will get to test it out a bit further tomorrow.
